language: java
jdk:
  - openjdk8
env:  
  global:  
    - DISPLAY=:99.0  
cache:
  directories:
   - $HOME/.m2

notifications:
  email:
    recipients:
      - vitruv-build@ira.uni-karlsruhe.de
  slack:
    secure: CyP313QKKADxO5T8q3P42DbYkCy37BXpjWNdZmEsv5xb/o02skPI9CdMbgIkqH5q3AowvPeE5z/tZo+nFRsC0VVStFlFwyf/d4X2zZ1ChJfEMkI2ovP5RTbKQ1HD5ibejOfgws7OFwG72UBXHQ8SDJnPkX7W8j8XxZU88gFaU+DpMcZZYiDRTkw2AgaCzLoYyuDashQ0DMMGLiOcVrUDJx24nihhcUDG93ibssV54a3GRM8778+J62Cy7urdgijMmK20Hva4ToKFwIocatqIzQMYFi39dqVUXQaErdLqGxdk2uG2JvISEgkLe99jLGxVSMd8exdnQTtvaf3zVNdlJOnQ8lZ1TlWZaNu37MfLkPg/7tExSyU5rpAVSVd6uHwIHY2GvyYZG1KZ4JgXWfh/eNbTMZzw7ePPKWQVYD1iG7X6tH28zYCpW4BMcako/vMzI2SxypXCbdtH45PVZb4nIUn0XRDtCJmllS2j0858ZVXn5O6EhmnF4dlmHIMfW/eShgA3Mcq5UFTj4cuHMQK2McLXv9/DXNUz4YXwV1RF2ltNSNSd7TlDsqov6NZ2LoiucFt3MiJVEPymntCrMgioQCH9WZ5/jSahXh1UQgQuX0eG5w+ycOyYhpz1XsT0DsiqJ4gz5L7Qbe1mhd94rNYyfRIgYta9V1wMsNAwDcFATEM=

# Enable UI
before_install:
    - sh -e /etc/init.d/xvfb start - sleep 10
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh applications/cbs releng/tools.vitruv.applications.cbs.updatesite repository vitruv-tools updatesite