language: java
sudo: false
jdk:
  - oraclejdk8
env:  
  global:  
    - DISPLAY=:99.0  
cache:
  directories:
   - $HOME/.m2

# Enable UI
before_install:
    - sh -e /etc/init.d/xvfb start - sleep 10
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/installMaven.sh
install: true

script: mvn clean verify